import { createContext, useContext, useEffect, useState } from 'react'

/* ─────────────────────────────────────────────────────────────────────────────
   Translations dictionary
   Keys are canonical English strings. Each language maps to its translation.
   Add new keys here as the app grows.
───────────────────────────────────────────────────────────────────────────── */
const TRANSLATIONS = {
  en: {
    // Nav
    'Feed':            'Feed',
    'Dashboard':       'Dashboard',
    'Profile':         'Profile',
    'Guide':           'Guide',
    'Logout':          'Logout',

    // Auth
    'Login':           'Login',
    'Register':        'Register',
    'Email':           'Email',
    'Password':        'Password',
    'Name':            'Name',
    'Sign in':         'Sign in',
    'Create account':  'Create account',
    'No account?':     'No account?',
    'Have account?':   'Have account?',

    // Profile / Settings
    'Settings':                  'Settings',
    'Save Changes':              'Save Changes',
    'Save Preferences':          'Save Preferences',
    'Update Password':           'Update Password',
    'Display Name':              'Display Name',
    'Bio':                       'Bio',
    'Skills':                    'Skills',
    'Experience Level':          'Experience Level',
    'beginner':                  'Beginner',
    'intermediate':              'Intermediate',
    'advanced':                  'Advanced',
    'Theme':                     'Theme',
    'Language':                  'Language',
    'Dark':                      'Dark',
    'Light':                     'Light',
    'Current Password':          'Current Password',
    'New Password':              'New Password',
    'GitHub Username':           'GitHub Username',
    'Personal Access Token (PAT)': 'Personal Access Token (PAT)',
    'Save Username':             'Save Username',
    'Verify & Save PAT':         'Verify & Save PAT',
    'Remove PAT':                'Remove PAT',
    'Profile updated!':          'Profile updated!',
    'Preferences saved!':        'Preferences saved!',
    'Password updated!':         'Password updated!',
    'GitHub PAT removed.':       'GitHub PAT removed.',
    'Avatar updated!':           'Avatar updated!',

    // Dashboard
    'My Projects':       'My Projects',
    'Create Project':    'Create Project',
    'No projects yet':   'No projects yet',
    'Join a project or create one to get started.': 'Join a project or create one to get started.',

    // Feed
    'Global Feed':       'Global Feed',
    'Write something…':  'Write something…',
    'Post':              'Post',
    'Like':              'Like',
    'Comment':           'Comment',
    'Share':             'Share',
    'just now':          'just now',
    'Attach':            'Attach',

    // Projects
    'Chat':              'Chat',
    'Gallery':           'Gallery',
    'Tasks':             'Tasks',
    'Members':           'Members',
    'Request to Join':   'Request to Join',
    'Pending':           'Pending',
    'Accept':            'Accept',
    'Decline':           'Decline',
    'Stars':             'Stars',
    'Forks':             'Forks',
    'Issues':            'Issues',

    // Task board
    'To Do':             'To Do',
    'In Progress':       'In Progress',
    'Done':              'Done',
    'Add Task':          'Add Task',
    'Save':              'Save',
    'Cancel':            'Cancel',
    'Delete':            'Delete',
    'Edit':              'Edit',
    'Required Skill':    'Required Skill',
    'Priority':          'Priority',
    'Assignee':          'Assignee',
    'Due Date':          'Due Date',

    // General
    'Send':              'Send',
    'Search':            'Search',
    'Loading…':          'Loading…',
    'Error':             'Error',
    'Close':             'Close',
    'Upload':            'Upload',
    'Copy':              'Copy',
    'Copied!':           'Copied!',
  },

  fr: {
    'Feed':            'Fil',
    'Dashboard':       'Tableau de bord',
    'Profile':         'Profil',
    'Guide':           'Guide',
    'Logout':          'Déconnexion',
    'Login':           'Connexion',
    'Register':        'Inscription',
    'Email':           'E-mail',
    'Password':        'Mot de passe',
    'Name':            'Nom',
    'Sign in':         'Se connecter',
    'Create account':  'Créer un compte',
    'No account?':     'Pas de compte ?',
    'Have account?':   'Déjà un compte ?',
    'Settings':                  'Paramètres',
    'Save Changes':              'Enregistrer',
    'Save Preferences':          'Sauvegarder les préférences',
    'Update Password':           'Changer le mot de passe',
    'Display Name':              'Nom affiché',
    'Bio':                       'Bio',
    'Skills':                    'Compétences',
    'Experience Level':          'Niveau d\'expérience',
    'beginner':                  'Débutant',
    'intermediate':              'Intermédiaire',
    'advanced':                  'Avancé',
    'Theme':                     'Thème',
    'Language':                  'Langue',
    'Dark':                      'Sombre',
    'Light':                     'Clair',
    'Current Password':          'Mot de passe actuel',
    'New Password':              'Nouveau mot de passe',
    'GitHub Username':           'Nom d\'utilisateur GitHub',
    'Personal Access Token (PAT)': 'Jeton d\'accès personnel (PAT)',
    'Save Username':             'Enregistrer le nom',
    'Verify & Save PAT':         'Vérifier et enregistrer le PAT',
    'Remove PAT':                'Supprimer le PAT',
    'Profile updated!':          'Profil mis à jour !',
    'Preferences saved!':        'Préférences sauvegardées !',
    'Password updated!':         'Mot de passe mis à jour !',
    'GitHub PAT removed.':       'PAT GitHub supprimé.',
    'Avatar updated!':           'Avatar mis à jour !',
    'My Projects':       'Mes projets',
    'Create Project':    'Créer un projet',
    'No projects yet':   'Aucun projet pour l\'instant',
    'Join a project or create one to get started.': 'Rejoignez ou créez un projet pour commencer.',
    'Global Feed':       'Fil mondial',
    'Write something…':  'Écrivez quelque chose…',
    'Post':              'Publier',
    'Like':              'J\'aime',
    'Comment':           'Commenter',
    'Share':             'Partager',
    'just now':          'à l\'instant',
    'Attach':            'Joindre',
    'Chat':              'Chat',
    'Gallery':           'Galerie',
    'Tasks':             'Tâches',
    'Members':           'Membres',
    'Request to Join':   'Demander à rejoindre',
    'Pending':           'En attente',
    'Accept':            'Accepter',
    'Decline':           'Refuser',
    'Stars':             'Étoiles',
    'Forks':             'Forks',
    'Issues':            'Problèmes',
    'To Do':             'À faire',
    'In Progress':       'En cours',
    'Done':              'Terminé',
    'Add Task':          'Ajouter une tâche',
    'Save':              'Enregistrer',
    'Cancel':            'Annuler',
    'Delete':            'Supprimer',
    'Edit':              'Modifier',
    'Required Skill':    'Compétence requise',
    'Priority':          'Priorité',
    'Assignee':          'Assigné à',
    'Due Date':          'Date limite',
    'Send':              'Envoyer',
    'Search':            'Rechercher',
    'Loading…':          'Chargement…',
    'Error':             'Erreur',
    'Close':             'Fermer',
    'Upload':            'Téléverser',
    'Copy':              'Copier',
    'Copied!':           'Copié !',
  },

  es: {
    'Feed':            'Noticias',
    'Dashboard':       'Panel',
    'Profile':         'Perfil',
    'Guide':           'Guía',
    'Logout':          'Cerrar sesión',
    'Login':           'Iniciar sesión',
    'Register':        'Registrarse',
    'Email':           'Correo',
    'Password':        'Contraseña',
    'Name':            'Nombre',
    'Sign in':         'Entrar',
    'Create account':  'Crear cuenta',
    'No account?':     '¿Sin cuenta?',
    'Have account?':   '¿Ya tienes cuenta?',
    'Settings':                  'Configuración',
    'Save Changes':              'Guardar cambios',
    'Save Preferences':          'Guardar preferencias',
    'Update Password':           'Actualizar contraseña',
    'Display Name':              'Nombre visible',
    'Bio':                       'Bio',
    'Skills':                    'Habilidades',
    'Experience Level':          'Nivel de experiencia',
    'beginner':                  'Principiante',
    'intermediate':              'Intermedio',
    'advanced':                  'Avanzado',
    'Theme':                     'Tema',
    'Language':                  'Idioma',
    'Dark':                      'Oscuro',
    'Light':                     'Claro',
    'Current Password':          'Contraseña actual',
    'New Password':              'Nueva contraseña',
    'GitHub Username':           'Usuario de GitHub',
    'Personal Access Token (PAT)': 'Token de acceso personal (PAT)',
    'Save Username':             'Guardar usuario',
    'Verify & Save PAT':         'Verificar y guardar PAT',
    'Remove PAT':                'Eliminar PAT',
    'Profile updated!':          '¡Perfil actualizado!',
    'Preferences saved!':        '¡Preferencias guardadas!',
    'Password updated!':         '¡Contraseña actualizada!',
    'GitHub PAT removed.':       'PAT de GitHub eliminado.',
    'Avatar updated!':           '¡Avatar actualizado!',
    'My Projects':       'Mis proyectos',
    'Create Project':    'Crear proyecto',
    'No projects yet':   'Sin proyectos aún',
    'Join a project or create one to get started.': 'Únete o crea un proyecto para comenzar.',
    'Global Feed':       'Noticias globales',
    'Write something…':  'Escribe algo…',
    'Post':              'Publicar',
    'Like':              'Me gusta',
    'Comment':           'Comentar',
    'Share':             'Compartir',
    'just now':          'ahora mismo',
    'Attach':            'Adjuntar',
    'Chat':              'Chat',
    'Gallery':           'Galería',
    'Tasks':             'Tareas',
    'Members':           'Miembros',
    'Request to Join':   'Solicitar unirse',
    'Pending':           'Pendiente',
    'Accept':            'Aceptar',
    'Decline':           'Rechazar',
    'Stars':             'Estrellas',
    'Forks':             'Forks',
    'Issues':            'Problemas',
    'To Do':             'Por hacer',
    'In Progress':       'En progreso',
    'Done':              'Hecho',
    'Add Task':          'Agregar tarea',
    'Save':              'Guardar',
    'Cancel':            'Cancelar',
    'Delete':            'Eliminar',
    'Edit':              'Editar',
    'Required Skill':    'Habilidad requerida',
    'Priority':          'Prioridad',
    'Assignee':          'Asignado',
    'Due Date':          'Fecha límite',
    'Send':              'Enviar',
    'Search':            'Buscar',
    'Loading…':          'Cargando…',
    'Error':             'Error',
    'Close':             'Cerrar',
    'Upload':            'Subir',
    'Copy':              'Copiar',
    'Copied!':           '¡Copiado!',
  },

  de: {
    'Feed':            'Feed',
    'Dashboard':       'Übersicht',
    'Profile':         'Profil',
    'Guide':           'Anleitung',
    'Logout':          'Abmelden',
    'Login':           'Anmelden',
    'Register':        'Registrieren',
    'Email':           'E-Mail',
    'Password':        'Passwort',
    'Name':            'Name',
    'Sign in':         'Einloggen',
    'Create account':  'Konto erstellen',
    'No account?':     'Kein Konto?',
    'Have account?':   'Bereits ein Konto?',
    'Settings':                  'Einstellungen',
    'Save Changes':              'Änderungen speichern',
    'Save Preferences':          'Einstellungen speichern',
    'Update Password':           'Passwort ändern',
    'Display Name':              'Anzeigename',
    'Bio':                       'Bio',
    'Skills':                    'Fähigkeiten',
    'Experience Level':          'Erfahrungsstufe',
    'beginner':                  'Anfänger',
    'intermediate':              'Mittelstufe',
    'advanced':                  'Fortgeschritten',
    'Theme':                     'Thema',
    'Language':                  'Sprache',
    'Dark':                      'Dunkel',
    'Light':                     'Hell',
    'Current Password':          'Aktuelles Passwort',
    'New Password':              'Neues Passwort',
    'GitHub Username':           'GitHub-Benutzername',
    'Personal Access Token (PAT)': 'Persönlicher Zugriffstoken (PAT)',
    'Save Username':             'Benutzername speichern',
    'Verify & Save PAT':         'PAT prüfen und speichern',
    'Remove PAT':                'PAT entfernen',
    'Profile updated!':          'Profil aktualisiert!',
    'Preferences saved!':        'Einstellungen gespeichert!',
    'Password updated!':         'Passwort aktualisiert!',
    'GitHub PAT removed.':       'GitHub-PAT entfernt.',
    'Avatar updated!':           'Avatar aktualisiert!',
    'My Projects':       'Meine Projekte',
    'Create Project':    'Projekt erstellen',
    'No projects yet':   'Noch keine Projekte',
    'Join a project or create one to get started.': 'Tritt einem Projekt bei oder erstelle eines.',
    'Global Feed':       'Globaler Feed',
    'Write something…':  'Schreib etwas…',
    'Post':              'Posten',
    'Like':              'Gefällt mir',
    'Comment':           'Kommentieren',
    'Share':             'Teilen',
    'just now':          'gerade eben',
    'Attach':            'Anhängen',
    'Chat':              'Chat',
    'Gallery':           'Galerie',
    'Tasks':             'Aufgaben',
    'Members':           'Mitglieder',
    'Request to Join':   'Beitritt beantragen',
    'Pending':           'Ausstehend',
    'Accept':            'Akzeptieren',
    'Decline':           'Ablehnen',
    'Stars':             'Sterne',
    'Forks':             'Forks',
    'Issues':            'Probleme',
    'To Do':             'Zu erledigen',
    'In Progress':       'In Bearbeitung',
    'Done':              'Erledigt',
    'Add Task':          'Aufgabe hinzufügen',
    'Save':              'Speichern',
    'Cancel':            'Abbrechen',
    'Delete':            'Löschen',
    'Edit':              'Bearbeiten',
    'Required Skill':    'Benötigte Fähigkeit',
    'Priority':          'Priorität',
    'Assignee':          'Beauftragte Person',
    'Due Date':          'Fälligkeitsdatum',
    'Send':              'Senden',
    'Search':            'Suchen',
    'Loading…':          'Laden…',
    'Error':             'Fehler',
    'Close':             'Schließen',
    'Upload':            'Hochladen',
    'Copy':              'Kopieren',
    'Copied!':           'Kopiert!',
  },

  zh: {
    'Feed':            '动态',
    'Dashboard':       '仪表板',
    'Profile':         '个人资料',
    'Guide':           '指南',
    'Logout':          '退出登录',
    'Login':           '登录',
    'Register':        '注册',
    'Email':           '邮箱',
    'Password':        '密码',
    'Name':            '姓名',
    'Sign in':         '登录',
    'Create account':  '创建账户',
    'No account?':     '没有账户？',
    'Have account?':   '已有账户？',
    'Settings':                  '设置',
    'Save Changes':              '保存更改',
    'Save Preferences':          '保存偏好',
    'Update Password':           '更新密码',
    'Display Name':              '显示名称',
    'Bio':                       '简介',
    'Skills':                    '技能',
    'Experience Level':          '经验等级',
    'beginner':                  '初学者',
    'intermediate':              '中级',
    'advanced':                  '高级',
    'Theme':                     '主题',
    'Language':                  '语言',
    'Dark':                      '深色',
    'Light':                     '浅色',
    'Current Password':          '当前密码',
    'New Password':              '新密码',
    'GitHub Username':           'GitHub 用户名',
    'Personal Access Token (PAT)': '个人访问令牌（PAT）',
    'Save Username':             '保存用户名',
    'Verify & Save PAT':         '验证并保存 PAT',
    'Remove PAT':                '移除 PAT',
    'Profile updated!':          '个人资料已更新！',
    'Preferences saved!':        '偏好已保存！',
    'Password updated!':         '密码已更新！',
    'GitHub PAT removed.':       'GitHub PAT 已移除。',
    'Avatar updated!':           '头像已更新！',
    'My Projects':       '我的项目',
    'Create Project':    '创建项目',
    'No projects yet':   '暂无项目',
    'Join a project or create one to get started.': '加入或创建一个项目以开始。',
    'Global Feed':       '全球动态',
    'Write something…':  '写点什么…',
    'Post':              '发布',
    'Like':              '点赞',
    'Comment':           '评论',
    'Share':             '分享',
    'just now':          '刚刚',
    'Attach':            '附件',
    'Chat':              '聊天',
    'Gallery':           '图库',
    'Tasks':             '任务',
    'Members':           '成员',
    'Request to Join':   '申请加入',
    'Pending':           '待处理',
    'Accept':            '接受',
    'Decline':           '拒绝',
    'Stars':             '星标',
    'Forks':             'Forks',
    'Issues':            '问题',
    'To Do':             '待办',
    'In Progress':       '进行中',
    'Done':              '完成',
    'Add Task':          '添加任务',
    'Save':              '保存',
    'Cancel':            '取消',
    'Delete':            '删除',
    'Edit':              '编辑',
    'Required Skill':    '所需技能',
    'Priority':          '优先级',
    'Assignee':          '负责人',
    'Due Date':          '截止日期',
    'Send':              '发送',
    'Search':            '搜索',
    'Loading…':          '加载中…',
    'Error':             '错误',
    'Close':             '关闭',
    'Upload':            '上传',
    'Copy':              '复制',
    'Copied!':           '已复制！',
  },

  ar: {
    'Feed':            'خلاصة',
    'Dashboard':       'لوحة التحكم',
    'Profile':         'الملف الشخصي',
    'Guide':           'الدليل',
    'Logout':          'تسجيل الخروج',
    'Login':           'تسجيل الدخول',
    'Register':        'إنشاء حساب',
    'Email':           'البريد الإلكتروني',
    'Password':        'كلمة المرور',
    'Name':            'الاسم',
    'Sign in':         'دخول',
    'Create account':  'إنشاء حساب',
    'No account?':     'ليس لديك حساب؟',
    'Have account?':   'لديك حساب بالفعل؟',
    'Settings':                  'الإعدادات',
    'Save Changes':              'حفظ التغييرات',
    'Save Preferences':          'حفظ التفضيلات',
    'Update Password':           'تحديث كلمة المرور',
    'Display Name':              'الاسم المعروض',
    'Bio':                       'نبذة',
    'Skills':                    'المهارات',
    'Experience Level':          'مستوى الخبرة',
    'beginner':                  'مبتدئ',
    'intermediate':              'متوسط',
    'advanced':                  'متقدم',
    'Theme':                     'المظهر',
    'Language':                  'اللغة',
    'Dark':                      'داكن',
    'Light':                     'فاتح',
    'Current Password':          'كلمة المرور الحالية',
    'New Password':              'كلمة المرور الجديدة',
    'GitHub Username':           'اسم مستخدم GitHub',
    'Personal Access Token (PAT)': 'رمز الوصول الشخصي (PAT)',
    'Save Username':             'حفظ اسم المستخدم',
    'Verify & Save PAT':         'التحقق وحفظ PAT',
    'Remove PAT':                'إزالة PAT',
    'Profile updated!':          'تم تحديث الملف الشخصي!',
    'Preferences saved!':        'تم حفظ التفضيلات!',
    'Password updated!':         'تم تحديث كلمة المرور!',
    'GitHub PAT removed.':       'تم إزالة PAT الخاص بـ GitHub.',
    'Avatar updated!':           'تم تحديث الصورة الرمزية!',
    'My Projects':       'مشاريعي',
    'Create Project':    'إنشاء مشروع',
    'No projects yet':   'لا توجد مشاريع بعد',
    'Join a project or create one to get started.': 'انضم أو أنشئ مشروعاً للبدء.',
    'Global Feed':       'الخلاصة العالمية',
    'Write something…':  'اكتب شيئاً…',
    'Post':              'نشر',
    'Like':              'إعجاب',
    'Comment':           'تعليق',
    'Share':             'مشاركة',
    'just now':          'الآن',
    'Attach':            'إرفاق',
    'Chat':              'دردشة',
    'Gallery':           'معرض',
    'Tasks':             'المهام',
    'Members':           'الأعضاء',
    'Request to Join':   'طلب الانضمام',
    'Pending':           'معلق',
    'Accept':            'قبول',
    'Decline':           'رفض',
    'Stars':             'النجوم',
    'Forks':             'التفرعات',
    'Issues':            'المشكلات',
    'To Do':             'للتنفيذ',
    'In Progress':       'قيد التنفيذ',
    'Done':              'منجز',
    'Add Task':          'إضافة مهمة',
    'Save':              'حفظ',
    'Cancel':            'إلغاء',
    'Delete':            'حذف',
    'Edit':              'تعديل',
    'Required Skill':    'المهارة المطلوبة',
    'Priority':          'الأولوية',
    'Assignee':          'المُكلَّف',
    'Due Date':          'تاريخ الاستحقاق',
    'Send':              'إرسال',
    'Search':            'بحث',
    'Loading…':          'جار التحميل…',
    'Error':             'خطأ',
    'Close':             'إغلاق',
    'Upload':            'رفع',
    'Copy':              'نسخ',
    'Copied!':           'تم النسخ!',
  },
}

/* ─────────────────────────────────────────────────────────────────────────────
   RTL languages
───────────────────────────────────────────────────────────────────────────── */
const RTL_LANGS = new Set(['ar'])

/* ─────────────────────────────────────────────────────────────────────────────
   Context
───────────────────────────────────────────────────────────────────────────── */
const Ctx = createContext(null)

export function LanguageProvider({ children, initialLang = 'en' }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem('language') || initialLang
  )

  function setLang(l) {
    setLangState(l)
    localStorage.setItem('language', l)
  }

  // Apply RTL direction to document
  useEffect(() => {
    const isRTL = RTL_LANGS.has(lang)
    document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr')
    document.documentElement.setAttribute('lang', lang)
  }, [lang])

  /** Translate a key. Falls back to the key itself if no translation found. */
  function t(key) {
    if (!key) return key
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en
    return dict[key] ?? TRANSLATIONS.en[key] ?? key
  }

  return (
    <Ctx.Provider value={{ lang, setLang, t, isRTL: RTL_LANGS.has(lang) }}>
      {children}
    </Ctx.Provider>
  )
}

export const useLanguage = () => useContext(Ctx)
