"""added fields 1

Revision ID: ee9fea4b4c83
Revises: 
Create Date: 2026-04-02 06:37:09.342017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9fea4b4c83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_pat', sa.Text(), nullable=True))
        batch_op.drop_column('github_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_token', sa.TEXT(), nullable=True))
        batch_op.drop_column('github_pat')

    # ### end Alembic commands ###
